name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  test:

    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v6.5.0
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Get current date and time
      if: always()
      run: echo "NOW=$(TZ='America/Sao_Paulo' date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: playwright-test-results-${{ env.NOW }}
        path: playwright-report/
        include-hidden-files: false
        overwrite: false
        if-no-files-found: warn
        compression-level: 0
        retention-days: 30
